### ISSUE TITLE
How to get full JSON response.body ?

### ISSUE THREAD

**Issue by adrianab** [robertodoering/twitter_api#17]
Hi I've created the following function below, I'm trying to fetch a list of tweets from a specific user and my plan is to get the full response.body JSON and add each tweet's subJson onto a List, but I'm unsure of how to get the full response.body from the API. Any help would be greatly appreciated, thank you!

```
      Future getTweets() async {
      String twitterID = '783214';
  
      Map<String, String> params = {
        'exclude': 'retweets,replies',
        'tweet.fields':
            'attachments,author_id,conversation_id,created_at,entities,referenced_tweets',
      };
  
      final jsonData = await twitterApi.client.get(
        Uri.https('api.twitter.com', '2/users/$twitterID/tweets', params),
      );
      
    }

```

**Comment by robertodoering** [comment]
Hey @adrianab,
The client returns a `Response` object on successful requests (2xx status code) and throws an exception otherwise.

In your example you can just call `jsonData.body` to get the json string from the response.

Using `jsonDecode` you can then parse the string into a `Map<String, dynamic>` for example.
```dart
final Map<String, dynamic> data = jsonDecode(jsonData.body);
```

---

On a side note, you probably don't want to use this package if you intend to exclusively access the Twitter API v2 because you will find yourself only using the `TwitterClient` of the `TwitterApi` to make authenticated requests.
You might as well depend on `oauth1` and copy the `TwitterClient` for your requests at that point.

**Comment by adrianab** [comment]
@robertodoering   Thank you for the quick response! I didn't actually realize it was that easy 😅. I was attempting to just fetch tweets for a given user in order to display them on a page as a list using this [tweet_ui library](https://github.com/schibsted/tweet_ui). Appreciate the help :)

**Comment by robertodoering** [comment]
No worries :) If you have any more questions don't hesitate to open up a new issue or comment on this one
